name: "Package oss-deployment"
on:
  push:
    branches:
      - main
      - feature/package_init
  workflow_dispatch:
jobs:
  lint_bash_files:
    name: lint_bash_files
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: run_shellcheck
        uses: ludeeus/action-shellcheck@master
  lint_env_files:
    name: lint_env_files
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: run_dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review # Default is github-pr-check
          dotenv_linter_flags: --skip UnorderedKey
  lint_yml_files:
    name: lint_yml_files
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: run_yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: true
          yamllint_comment: false

  package_install_code:
    name: lint_bash_code
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: Create tar.gz Package
        run: |
          tar -czvf ./repository.tar.gz --exclude=".git" --exclude=".github" .